chatspace_非同期通信_jsファイル作成
chabikun/chat-space pull request #28
Opened 2019-02-03 12:51 UTC by chabikun

# WHAT
非同期崇信を記述するjsファイルを作成する
# WHY
- chat-spaceのメッセージ送信機能を非同期通信で行うため
- jquery を記述するファイルを用意

2019-02-03 12:57 UTC, yuki-uchida requested changes
プルリクに何も反映されていないので、もう一度確認お願いいたします

2019-02-09 07:00 UTC, chabikun commented
# WHAT
非同期通信の実装が完了
## app/assets/javascripts/application.js
- メッセージ送信の際に同期通信になってしまうのを防ぐために削除
## app/assets/javascripts/message.js
- 非同期通信に情報受け渡しを実現するための記述
## app/assets/stylesheets/_main.scss
- メッセージ数が多くなり見切れてしまう場合にスクロールできるようにする
## app/controllers/groups_controller.rb
- ルートの表示がされない状態だったので、groupsコントローラーへindexを用意
- 同じくupdate後の記述が漏れていたので追加
## app/controllers/messages_controller.rb
- 非同期通信とHTML型で情報を受け取る際の分岐を記述
## app/views/groups/index.html.haml
- ルートの表示がされない状態だったので用意
## app/views/messages/create.json.jbuilder
- 非同期通信で使用するJSON形式のデータを定義
## config/routes.rb
- ルートの表示がされない状態だったので用意
# WHY
- chat-spaceのメッセージ送信機能を非同期通信で行うため
- 非同期通信を実装することによりユーザビリティを向上させる

2019-02-09 07:02 UTC, chabikun commented
<img width="1440" alt="2019-02-09 16 01 59" src="https://user-images.githubusercontent.com/45908284/52517794-1a4bef00-2c84-11e9-8c07-5c3bf0f64233.png">

2019-02-09 07:47 UTC, TOMARUMARU reviewed
画像を送信できるようになってなさそうなので実装してください

2019-02-10 11:42 UTC, chabikun commented
# WHAT
## レヴュー指摘事項を修正しました
非同期で画像送信できるようにする
# WHY
画像送信を非同期通信で可能にするため

2019-02-10 11:48 UTC, ghost requested changes

2019-02-10 11:48 UTC, hiroki5123 commented on app/views/groups/index.html.haml
> +      %ul{class: "side-bar-icon"}
%ul.side-bar-icon
でいける気がします。
省略できるところは省略していきましょう

2019-02-10 11:48 UTC, hiroki5123 commented on app/views/groups/index.html.haml
> +          %i{class: "far fa-edit edit-icon-color"}
こちらも

2019-02-10 11:48 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +      $('#message_image').val('')
reset()を使いたいです

2019-02-10 11:48 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +      return html_nil
いまのままでは、画像を送った時も二つの半数が作られるため、この中でhtmlを組み立てましょう

2019-02-10 12:31 UTC, chabikun commented on app/views/groups/index.html.haml
> +      %ul{class: "side-bar-icon"}
削除しました。

2019-02-10 12:31 UTC, chabikun commented on app/views/groups/index.html.haml
> +          %i{class: "far fa-edit edit-icon-color"}
削除しました。

2019-02-10 12:32 UTC, chabikun commented on app/assets/javascripts/message.js
> +      $('#message_image').val('')
reset()にした方が良い理由を教えていただけますか？

2019-02-10 12:40 UTC, chabikun commented on app/assets/javascripts/message.js
> +      return html_nil
nilの時をif分の中に記述しました。

2019-02-10 12:57 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +      $('#message_image').val('')
$('.message').val('')
$('#message_image').val('')
の部分を1行で表現できるためです。

2019-02-10 12:57 UTC, ghost approved these changes

2019-02-10 13:15 UTC, chabikun commented on app/assets/javascripts/message.js
> +      $('#message_image').val('')
ご返信ありがとうございます。

理解しました。

2019-02-10 13:24 UTC, chabikun commented
ありがとうございます！

iPadから送信

2019/02/10 21:57、hiroki-ichikawa <notifications@github.com>のメール:

> @hiroki5123 approved this pull request.
> 
> LGTMです！
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-02-11 12:05 UTC, merged