Add マークダウン
chabikun/chat-space pull request #3
Opened 2019-01-06 09:22 UTC by chabikun

# WHAT
READMEへデータベースの記述をしました

# WHY
カリキュラム課題
マークダウンの練習

2019-01-06 09:30 UTC, kuroko918 commented
memberだけでなく、user、group、messageの設計についても記述してください！

2019-01-06 10:31 UTC, kuroko918 reviewed
一旦修正お願いします！

2019-01-06 10:31 UTC, kuroko918 commented on README.md
> +
この行より下の行は使用しないので消しましょう！

2019-01-06 10:31 UTC, kuroko918 commented on README.md
> +- has_many :groups
throughが抜けています！

2019-01-06 10:31 UTC, kuroko918 commented on README.md
> +- has_many :members
これはいらないかと思います！

2019-01-06 10:31 UTC, kuroko918 commented on README.md
> +- hbelongs_ to :user
belongs_toではないかと思います！
throughも含めて書き直してください！

2019-01-06 10:31 UTC, kuroko918 commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
integer型だとforeign_keyによる外部キー制約が効かないので、references型に変更しましょう！

2019-01-06 10:31 UTC, kuroko918 commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
integer型だとforeign_keyによる外部キー制約が効かないので、references型に変更しましょう！

2019-01-06 10:31 UTC, kuroko918 commented on README.md
> +|group_id|integer|null:false, foreign_key: true|
integer型だとforeign_keyによる外部キー制約が効かないので、references型に変更しましょう！

2019-01-06 10:31 UTC, kuroko918 commented on README.md
> +|user_id|integer|null:false, foreign_key: true|
integer型だとforeign_keyによる外部キー制約が効かないので、references型に変更しましょう！

2019-01-06 10:31 UTC, kuroko918 commented on README.md
> +|membaer_id|integer|null:false, foreign_key: true|
has_meny :memberなのに、memberの外部キーはいらないです。

2019-01-06 10:31 UTC, kuroko918 commented on README.md
> +|user_id|integer|null:false, foreign_key: true|
has_meny :userなので、userの外部キーはいらないです。

2019-01-08 10:14 UTC, hiroki5123 commented on README.md
> +- has_many :groups, through: :group_users
ここのgroups_usersに誤りがあります

2019-01-08 10:14 UTC, hiroki5123 commented on README.md
> +- has_many :groups
アソシエーションに誤りがあります

2019-01-08 10:14 UTC, hiroki5123 commented on README.md
> +- has_ many :users, through: :users_users
users_usersとは。。。

2019-01-09 05:33 UTC, miyagit commented on README.md
> +- has_many :users, through: :members_id
idじゃなくて中間テーブルですね。

2019-01-09 05:33 UTC, miyagit commented on README.md
> +- has_many :groups
こちら修正されていません。
分からなければメンターに聞きましょう。

2019-01-09 12:40 UTC, hiroki5123 commented on README.md
> +|groupname|text|null:false|
groupsテーブルなのでnameでいいと思います

2019-01-09 12:40 UTC, ghost requested changes
あとちょっとです

2019-01-10 12:18 UTC, yutakatahira commented
LGTMです。

2019-01-10 13:02 UTC, chabikun commented
ありがとうございます！

2019-01-10 13:08 UTC, merged